version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/bsc-js-backend" # Location of package manifests
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    target-branch: "npm-backend"
    labels:
      - "tag > bot"
      - "kind > dependencies"
      - "scope > backend"

  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/bulak-smart-connect-js" # Location of package manifests
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    target-branch: "npm-frontend"
    labels:
      - "tag > bot"
      - "kind > dependencies"
      - "scope > frontend"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10