name: API Documentation

on:
  push:
    branches: [ '*']
    paths:
      - 'bsc-js-backend/src/**'
      - 'bsc-js-backend/docs/**'
      - '.github/workflows/api-documentation.yml'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'bsc-js-backend/package-lock.json'
      
      - name: Install dependencies
        run: |
          cd bsc-js-backend
          npm ci
          npm install --save-dev @compodoc/compodoc
      
      - name: Check tsconfig.json exists
        run: |
          if [ ! -f "bsc-js-backend/tsconfig.json" ]; then
            echo "Error: tsconfig.json not found in bsc-js-backend directory"
            echo "Creating a basic tsconfig.json file"
            echo '{
              "compilerOptions": {
                "target": "es2017",
                "module": "commonjs",
                "declaration": true,
                "removeComments": true,
                "emitDecoratorMetadata": true,
                "experimentalDecorators": true,
                "sourceMap": true,
                "outDir": "./dist",
                "baseUrl": "./",
                "incremental": true
              },
              "include": ["src/**/*"],
              "exclude": ["node_modules", "dist"]
            }' > bsc-js-backend/tsconfig.json
          fi
      
      - name: Create docs directory if not exists
        run: mkdir -p bsc-js-backend/docs
      
      - name: Generate API documentation
        run: |
          cd bsc-js-backend
          npx @compodoc/compodoc -p tsconfig.json -d docs/api
      
      - name: Add root .nojekyll file
        run: |
          # Create a .nojekyll file to tell GitHub not to process with Jekyll
          touch bsc-js-backend/docs/api/.nojekyll
          
          # Create a README.md to explain the docs site
          echo "# API Documentation for Bulak Smart Connect JS
          
          This branch contains automatically generated API documentation using Compodoc.
          
          [View the documentation site](https://yukarlo15.github.io/Bulak-Smart-Connect-JS/api-docs/)
          " > bsc-js-backend/docs/api/README.md

      - name: Debug docs output
        run: |
          ls -la bsc-js-backend/docs/api || echo "API docs directory not found"
      
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: bsc-js-backend/docs/api
          target-folder: api-docs
          clean: true        # Important: clean old files
          clean-exclude: |   # Don't delete important files at the root
            .nojekyll
          branch: gh-pages

      - name: Ensure root .nojekyll exists
        run: |
          # Create a temporary directory
          mkdir -p temp_root
          
          # Create a .nojekyll file
          touch temp_root/.nojekyll
          
          # Create a simple index.html that redirects to the API docs
          echo '<!DOCTYPE html>
          <html>
            <head>
              <meta http-equiv="refresh" content="0; url=api-docs/">
            </head>
          </html>' > temp_root/index.html
          
          # Install gh-pages explicitly first
          npm install -g gh-pages
          
          # Deploy to root of gh-pages branch without cleaning existing files
          gh-pages -d temp_root -t --dotfiles