name: CI/CD Pipeline

on:
  push:
    branches: ['**']  # Run on all branches
  pull_request:
    branches: ['**']  # Run on PRs to any branch
  workflow_dispatch:  # Allow manual trigger

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x, 22.x]  # Supporting current LTS and your local version

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run linting
      run: npm run lint || echo "Linting not configured"
      
    - name: Run tests
      run: npm test || echo "No tests found"
      
    - name: Build project
      run: npm run build || echo "Build script not configured"
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-files-node-${{ matrix.node-version }}
        path: |
          build
          dist
        if-no-files-found: ignore