name: Frontend Documentation

on:
  push:
    branches: [ '*']
    paths:
      - 'bulak-smart-connect-js/src/**'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-frontend-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'bulak-smart-connect-js/package-lock.json'
      
      - name: Install dependencies
        run: |
          cd bulak-smart-connect-js
          npm ci
          npm install --save-dev react-styleguidist
      
      - name: Generate frontend documentation
        run: |
          cd bulak-smart-connect-js
          
          # Create styleguide.config.cjs instead of .js
          cat > styleguide.config.cjs << 'EOF'
          const path = require('path');
          
          module.exports = {
            title: 'Bulak Smart Connect React Components',
            components: [
              'src/**/UserBulakSmartConnect/**/*.jsx',
              'src/**/AdminBulakSmartConnect/**/*.jsx',
              'src/**/LandingPageComponents/**/*.jsx',
              'src/**/LogInComponents/**/*.jsx',
              'src/**/NavigationComponents/**/*.jsx',
              'src/**/components/**/*.jsx',
            ],
            ignore: [
              '**/__tests__/**',
              '**/*.test.jsx',
              '**/*.spec.jsx',
              '**/node_modules/**',
              '**/*.js',
              '**/index.jsx'
            ],
            template: {
              head: {
                links: [
                  {
                    rel: 'stylesheet',
                    href: 'https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap'
                  }
                ]
              }
            },
            webpackConfig: {
              module: {
                rules: [
                  {
                    test: /\.(js|jsx)$/,
                    exclude: /node_modules/,
                    use: {
                      loader: 'babel-loader',
                      options: {
                        presets: ['@babel/preset-env', '@babel/preset-react']
                      }
                    }
                  },
                  {
                    test: /\.css$/,
                    use: ['style-loader', 'css-loader']
                  },
                  {
                    test: /\.(png|jpg|gif|svg)$/,
                    use: [
                      {
                        loader: 'file-loader',
                        options: {
                          name: '[name].[ext]',
                          outputPath: 'images/'
                        }
                      }
                    ]
                  }
                ]
              }
            }
          };
          EOF
          
          # Install dependencies (unchanged)
          npm install --save-dev babel-loader @babel/preset-env @babel/preset-react style-loader css-loader file-loader
          
          # Run with the .cjs extension
          npx styleguidist build --config styleguide.config.cjs
          
          # Ensure output directory exists and copy files
          mkdir -p docs/frontend
          cp -r styleguide/* docs/frontend/ || echo "No styleguide directory found"
      
      - name: Fix placeholder image paths
        run: |
          cd bulak-smart-connect-js
          # Use sed to replace the placeholder path with a solid background color
          sed -i 's|background-image: url('"'"'path/to/your/background-image.jpg'"'"');|background-color: #f0f0f0;|g' src/AdminBulakSmartConnect/AccountManagementComponents/ProfileUpload.css
      
      - name: Create documentation hub
        run: |
          mkdir -p doc_hub
          touch doc_hub/.nojekyll
          
          echo '<!DOCTYPE html>
          <html>
            <head>
              <meta charset="utf-8">
              <title>Bulak Smart Connect Documentation Hub</title>
              <style>
                body { font-family: Arial, sans-serif; max-width: 800px; margin: 0 auto; padding: 20px; }
                .card { border: 1px solid #ddd; border-radius: 8px; padding: 16px; margin: 16px 0; }
                .button { display: inline-block; background-color: #4CAF50; color: white; padding: 10px 20px; 
                          text-decoration: none; border-radius: 4px; }
              </style>
            </head>
            <body>
              <h1>Bulak Smart Connect Documentation</h1>
              
              <div class="card">
                <h2>API Documentation</h2>
                <p>Backend API documentation generated with Compodoc.</p>
                <a href="api-docs/" class="button">View API Docs</a>
              </div>
              
              <div class="card">
                <h2>Frontend Documentation</h2>
                <p>Frontend component and service documentation.</p>
                <a href="frontend-docs/" class="button">View Frontend Docs</a>
              </div>
            </body>
          </html>' > doc_hub/index.html
      
      - name: Deploy frontend docs
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: bulak-smart-connect-js/docs/frontend
          target-folder: frontend-docs
          branch: gh-pages
          clean: true
          clean-exclude: |
            .nojekyll
            api-docs/**

      - name: Deploy documentation hub
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: doc_hub
          branch: gh-pages
          clean: false