name: PR Checks

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  conventional-commits:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Check commit messages
        uses: wagoid/commitlint-github-action@v5
  
  required-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check for serviceAccountKey
        run: |
          if [ ! -f "bsc-js-backend/src/config/serviceAccountKey.json" ]; then
            echo "Warning: serviceAccountKey.json is missing. This file is required for development but should not be committed to the repository."
          fi