name: Security Scanning

on:
  push:
    branches: [workflows]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 0 * * 0' # Run weekly at midnight on Sunday

jobs:
  security:
    name: Security Scan
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Run npm audit (Frontend)
        run: |
          cd bulak-smart-connect-js
          npm audit --audit-level=high
      
      - name: Run npm audit (Backend)
        run: |
          cd bsc-js-backend
          npm audit --audit-level=high
          
      - name: Run CodeQL Analysis
        uses: github/codeql-action/init@v3
        with:
          languages: javascript, typescript
      
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3